export const ayacuchoData = {
  provinces: {
    Huamanga: [
      "Ayacucho",
      "Acocro",
      "Acos Vinchos",
      "Carmen Alto",
      "Chiara",
      "Ocros",
      "Pacaycasa",
      "Quinua",
      "San José de Ticllas",
      "San Juan Bautista",
      "Santiago de Pischa",
      "Socos",
      "Tambillo",
      "Vinchos",
      "Jesús Nazareno",
    ],
    Cangallo: ["Cangallo", "Chuschi", "Los Morochucos", "María Parado de Bellido", "Paras", "Totos"],
    "Huanca Sancos": ["Sancos", "Carapo", "Sacsamarca", "Santiago de Lucanamarca"],
    Huanta: ["Huanta", "Ayahuanco", "Huamanguilla", "Iguaín", "Luricocha", "Santillana", "Sivia", "Llochegua"],
    "La Mar": ["San Miguel", "Anco", "Ayna", "Chilcas", "Chungui", "Luis Carranza", "Santa Rosa", "Tambo"],
    Lucanas: [
      "Puquio",
      "Aucara",
      "Cabana",
      "Carmen Salcedo",
      "Chaviña",
      "Chipao",
      "Huac-Huas",
      "Laramate",
      "Leoncio Prado",
      "Llauta",
      "Lucanas",
      "Ocaña",
      "Otoca",
      "Saisa",
      "San Cristóbal",
      "San Juan",
      "San Pedro",
      "San Pedro de Palco",
      "Sancos",
      "Santa Ana de Huaycahuacho",
      "Santa Lucia",
    ],
    Parinacochas: [
      "Coracora",
      "Chumpi",
      "Coronel Castañeda",
      "Pacapausa",
      "Pullo",
      "Puyusca",
      "San Francisco de Ravacayco",
      "Upahuacho",
    ],
    "Páucar del Sara Sara": [
      "Pausa",
      "Colta",
      "Corculla",
      "Lampa",
      "Marcabamba",
      "Oyolo",
      "Pararca",
      "San Javier de Alpabamba",
      "San José de Ushua",
      "Sara Sara",
    ],
    Sucre: [
      "Querobamba",
      "Belén",
      "Chalcos",
      "Chilcayoc",
      "Huacaña",
      "Morcolla",
      "Paico",
      "San Pedro de Larcay",
      "San Salvador de Quije",
      "Santiago de Paucaray",
      "Soras",
    ],
    "Víctor Fajardo": [
      "Huancapi",
      "Alcamenca",
      "Apongo",
      "Asquipata",
      "Canaria",
      "Cayara",
      "Colca",
      "Huamanquiquia",
      "Huancaraylla",
      "Huaya",
      "Sarhua",
      "Vilcanchos",
    ],
    "Vilcas Huamán": [
      "Vilcas Huamán",
      "Accomarca",
      "Carhuanca",
      "Concepción",
      "Huambalpa",
      "Independencia",
      "Saurama",
      "Vischongo",
    ],
  },
}
