export const products = [
  // FIGURAS
  {
    id: 1,
    name: "Figura Naruto Uzumaki Sage Mode",
    price: 89.99,
    originalPrice: 120.0,
    image: "/img/figuras/img1.jpg",
    category: "figuras",
    franchise: "Naruto",
    rating: 4.8,
    reviews: 124,
    description:
      "Figura de Naruto en modo sabio, con detalles increíbles y articulaciones móviles.",
    isNew: true,
  },
  {
    id: 2,
    name: "Figura Goku Ultra Instinct",
    price: 129.99,
    originalPrice: 160.0,
    image: "/img/figuras/img2.jpg",
    category: "figuras",
    franchise: "Dragon Ball",
    rating: 4.9,
    reviews: 95,
    description: "Figura premium de Goku con efectos de energía incluidos.",
    isNew: true,
  },
  {
    id: 3,
    name: "Figura Luffy Gear 5",
    price: 99.99,
    originalPrice: 140.0,
    image: "/img/figuras/img3.jpg",
    category: "figuras",
    franchise: "One Piece",
    rating: 4.7,
    reviews: 87,
    description: "Figura detallada de Luffy en su transformación Gear 5.",
  },
  {
    id: 4,
    name: "Figura Tanjiro Kamado con katana",
    price: 84.99,
    originalPrice: 110.0,
    image: "/img/figuras/img4.jpg",
    category: "figuras",
    franchise: "Demon Slayer",
    rating: 4.6,
    reviews: 102,
    description: "Tanjiro listo para la batalla con su icónica katana.",
  },
  {
    id: 5,
    name: "Figura Levi Ackerman Acción",
    price: 89.99,
    originalPrice: 115.0,
    image: "/img/figuras/img5.jpg",
    category: "figuras",
    franchise: "Attack on Titan",
    rating: 4.9,
    reviews: 134,
    description:
      "Figura articulada de Levi con su equipo de maniobras tridimensional.",
    isHot: true,
  },
  {
    id: 6,
    name: "Figura Itachi Uchiha",
    price: 94.99,
    originalPrice: 130.0,
    image: "/img/figuras/img6.jpg",
    category: "figuras",
    franchise: "Naruto",
    rating: 4.8,
    reviews: 76,
    description: "Itachi en pose clásica con el sharingan activado.",
  },
  {
    id: 7,
    name: "Figura Vegeta Final Flash",
    price: 109.99,
    originalPrice: 145.0,
    image: "/img/figuras/img7.jpg",
    category: "figuras",
    franchise: "Dragon Ball",
    rating: 4.7,
    reviews: 91,
    description: "Figura poderosa de Vegeta con base iluminada.",
  },
  {
    id: 8,
    name: "Figura Nezuko Kamado Demon Form",
    price: 75.99,
    originalPrice: 100.0,
    image: "/img/figuras/img8.jpg",
    category: "figuras",
    franchise: "Demon Slayer",
    rating: 4.6,
    reviews: 66,
    description: "Nezuko en forma demonio con detalles finos.",
  },
  {
    id: 9,
    name: "Figura Shingeki no Kyojin Eren Titan",
    price: 119.99,
    originalPrice: 150.0,
    image: "/img/figuras/img9.jpg",
    category: "figuras",
    franchise: "Attack on Titan",
    rating: 4.5,
    reviews: 58,
    description: "Eren en su forma de Titán de Ataque en pose imponente.",
  },
  {
    id: 10,
    name: "Figura Kakashi Hatake con Chidori",
    price: 92.99,
    originalPrice: 125.0,
    image: "/img/figuras/img10.jpg",
    category: "figuras",
    franchise: "Naruto",
    rating: 4.8,
    reviews: 108,
    description: "Figura dinámica de Kakashi usando su técnica Chidori.",
  },

  // MANGAS
  {
    id: 11,
    name: "Manga Attack on Titan Vol. 1-10",
    price: 149.99,
    originalPrice: 200.0,
    image: "/img/mangas/img1.jpg",
    category: "mangas",
    franchise: "Attack on Titan",
    rating: 4.9,
    reviews: 89,
    description: "Colección completa de los primeros 10 volúmenes en español.",
    isHot: true,
  },
  {
    id: 12,
    name: "Manga Naruto Vol. 1-5",
    price: 79.99,
    originalPrice: 100.0,
    image: "/img/mangas/img2.jpg",
    category: "mangas",
    franchise: "Naruto",
    rating: 4.8,
    reviews: 54,
    description: "Inicio de la historia de Naruto desde su infancia.",
  },
  {
    id: 13,
    name: "Manga One Piece Vol. 1-3",
    price: 39.99,
    originalPrice: 60.0,
    image: "/img/mangas/img3.jpg",
    category: "mangas",
    franchise: "One Piece",
    rating: 4.6,
    reviews: 47,
    description: "Primeros volúmenes de la gran aventura de Luffy.",
  },
  {
    id: 14,
    name: "Manga Demon Slayer Box Vol. 1-11",
    price: 159.99,
    originalPrice: 210.0,
    image: "/img/mangas/img4.jpg",
    category: "mangas",
    franchise: "Demon Slayer",
    rating: 4.9,
    reviews: 63,
    description: "Edición box con los primeros 11 volúmenes.",
  },
  {
    id: 15,
    name: "Manga Dragon Ball Z Saga Saiyan",
    price: 89.99,
    originalPrice: 120.0,
    image: "/img/mangas/img5.jpg",
    category: "mangas",
    franchise: "Dragon Ball",
    rating: 4.7,
    reviews: 52,
    description: "Revive la saga de los Saiyajin con Goku y Vegeta.",
  },
  {
    id: 16,
    name: "Manga Tokyo Revengers Vol. 1",
    price: 14.99,
    originalPrice: 20.0,
    image: "/img/mangas/img6.jpg",
    category: "mangas",
    franchise: "Tokyo Revengers",
    rating: 4.5,
    reviews: 21,
    description: "Un viaje al pasado para salvar al amor de su vida.",
  },
  {
    id: 17,
    name: "Manga Chainsaw Man Vol. 1",
    price: 13.99,
    originalPrice: 18.0,
    image: "/img/mangas/img7.jpg",
    category: "mangas",
    franchise: "Chainsaw Man",
    rating: 4.7,
    reviews: 29,
    description: "El inicio de una historia sangrienta y caótica.",
  },
  {
    id: 18,
    name: "Manga Fullmetal Alchemist Vol. 1-3",
    price: 39.99,
    originalPrice: 55.0,
    image: "/img/mangas/img8.jpg",
    category: "mangas",
    franchise: "Fullmetal Alchemist",
    rating: 4.8,
    reviews: 36,
    description: "Primeros volúmenes de una épica historia de alquimia.",
  },
  {
    id: 19,
    name: "Manga Death Note Vol. 1",
    price: 11.99,
    originalPrice: 15.0,
    image: "/img/mangas/img9.jpg",
    category: "mangas",
    franchise: "Death Note",
    rating: 4.9,
    reviews: 92,
    description:
      "¿Qué harías si tuvieras el poder de decidir quién vive y quién muere?",
  },
  {
    id: 20,
    name: "Manga Bleach Vol. 1-5",
    price: 74.99,
    originalPrice: 100.0,
    image: "/img/mangas/img10.jpg",
    category: "mangas",
    franchise: "Bleach",
    rating: 4.6,
    reviews: 38,
    description: "Ichigo Kurosaki y el inicio de sus aventuras como shinigami.",
  },
  // ROPA
  {
    id: 21,
    name: "Hoodie Dragon Ball Z Goku",
    price: 59.99,
    originalPrice: 80.0,
    image: "/img/ropa/img1.jpg",
    category: "ropa",
    franchise: "Dragon Ball",
    rating: 4.7,
    reviews: 156,
    description: "Sudadera con diseño exclusivo de Goku Super Saiyan.",
    isNew: true,
  },
  {
    id: 22,
    name: "Polo Naruto Akatsuki",
    price: 29.99,
    originalPrice: 45.0,
    image: "/img/ropa/img2.jpg",
    category: "ropa",
    franchise: "Naruto",
    rating: 4.6,
    reviews: 98,
    description: "Polo con el símbolo de la organización Akatsuki.",
  },
  {
    id: 23,
    name: "Casaca One Piece Luffy",
    price: 69.99,
    originalPrice: 90.0,
    image: "/img/ropa/img3.jpg",
    category: "ropa",
    franchise: "One Piece",
    rating: 4.8,
    reviews: 72,
    description: "Casaca estilo pirata con detalles de Luffy.",
  },
  {
    id: 24,
    name: "Pantalón Deportivo Demon Slayer",
    price: 39.99,
    originalPrice: 55.0,
    image: "/img/ropa/img4.jpg",
    category: "ropa",
    franchise: "Demon Slayer",
    rating: 4.5,
    reviews: 64,
    description: "Cómodo pantalón con diseños de Kimetsu no Yaiba.",
  },
  {
    id: 25,
    name: "Polo Tokyo Revengers Toman",
    price: 25.99,
    originalPrice: 35.0,
    image: "/img/ropa/img5.jpg",
    category: "ropa",
    franchise: "Tokyo Revengers",
    rating: 4.6,
    reviews: 52,
    description: "Polo oficial del emblema Toman en algodón premium.",
  },
  {
    id: 26,
    name: "Gorra Death Note L",
    price: 19.99,
    originalPrice: 30.0,
    image: "/img/ropa/img6.jpg",
    category: "ropa",
    franchise: "Death Note",
    rating: 4.4,
    reviews: 33,
    description: "Gorra ajustable con el logotipo de L.",
  },
  {
    id: 27,
    name: "Hoodie Bleach Ichigo",
    price: 54.99,
    originalPrice: 75.0,
    image: "/img/ropa/img7.jpg",
    category: "ropa",
    franchise: "Bleach",
    rating: 4.7,
    reviews: 47,
    description: "Sudadera con diseño de Ichigo y la Zangetsu.",
  },
  {
    id: 28,
    name: "Pijama Nezuko Chibi",
    price: 44.99,
    originalPrice: 60.0,
    image: "/img/ropa/img8.jpg",
    category: "ropa",
    franchise: "Demon Slayer",
    rating: 4.5,
    reviews: 58,
    description: "Pijama suave con diseño adorable de Nezuko chibi.",
  },
  {
    id: 29,
    name: "Camiseta Chainsaw Man Denji",
    price: 22.99,
    originalPrice: 35.0,
    image: "/img/ropa/img9.jpg",
    category: "ropa",
    franchise: "Chainsaw Man",
    rating: 4.6,
    reviews: 41,
    description:
      "Camiseta de algodón con ilustración de Denji en modo Chainsaw.",
  },
  {
    id: 30,
    name: "Polera Fullmetal Alchemist",
    price: 49.99,
    originalPrice: 70.0,
    image: "/img/ropa/img10.jpg",
    category: "ropa",
    franchise: "Fullmetal Alchemist",
    rating: 4.8,
    reviews: 39,
    description: "Diseño único de Edward Elric y el sello de transmutación.",
  },

  // TAZAS
  {
    id: 31,
    name: "Taza Térmica One Piece Luffy",
    price: 24.99,
    originalPrice: 35.0,
    image: "/img/tazas/img1.jpg",
    category: "tazas",
    franchise: "One Piece",
    rating: 4.6,
    reviews: 203,
    description: "Taza que revela el Gear 4 con el calor.",
    isHot: true,
  },
  {
    id: 32,
    name: "Taza Naruto Kurama",
    price: 19.99,
    originalPrice: 28.0,
    image: "/img/tazas/img2.jpg",
    category: "tazas",
    franchise: "Naruto",
    rating: 4.5,
    reviews: 143,
    description: "Taza con diseño interior de Kurama en modo chakra.",
  },
  {
    id: 33,
    name: "Taza Goku vs Vegeta",
    price: 21.99,
    originalPrice: 30.0,
    image: "/img/tazas/img3.jpg",
    category: "tazas",
    franchise: "Dragon Ball",
    rating: 4.7,
    reviews: 89,
    description: "Taza de combate épico entre Goku y Vegeta.",
  },
  {
    id: 34,
    name: "Taza de Alquimia Fullmetal",
    price: 18.99,
    originalPrice: 25.0,
    image: "/img/tazas/img4.jpg",
    category: "tazas",
    franchise: "Fullmetal Alchemist",
    rating: 4.6,
    reviews: 64,
    description: "Taza con sello de transmutación en tinta negra.",
  },
  {
    id: 35,
    name: "Taza Demon Slayer Hashira",
    price: 23.99,
    originalPrice: 32.0,
    image: "/img/tazas/img5.jpg",
    category: "tazas",
    franchise: "Demon Slayer",
    rating: 4.5,
    reviews: 112,
    description: "Taza de cerámica con los Hashira en pose de batalla.",
  },
  {
    id: 36,
    name: "Taza Tokyo Revengers Mikey",
    price: 20.99,
    originalPrice: 27.0,
    image: "/img/tazas/img6.jpg",
    category: "tazas",
    franchise: "Tokyo Revengers",
    rating: 4.4,
    reviews: 49,
    description: "Diseño minimalista de Mikey a un lado y el logo Toman.",
  },
  {
    id: 37,
    name: "Taza Bleach Hollow Ichigo",
    price: 19.49,
    originalPrice: 26.0,
    image: "/img/tazas/img7.jpg",
    category: "tazas",
    franchise: "Bleach",
    rating: 4.5,
    reviews: 37,
    description: "Taza blanca con rostro Hollow de Ichigo.",
  },
  {
    id: 38,
    name: "Taza Chibi Nezuko Bamboo",
    price: 18.99,
    originalPrice: 24.0,
    image: "/img/tazas/img8.jpg",
    category: "tazas",
    franchise: "Demon Slayer",
    rating: 4.6,
    reviews: 76,
    description: "Diseño adorable de Nezuko con su bambú.",
  },
  {
    id: 39,
    name: "Taza Chainsaw Man Sangrienta",
    price: 22.99,
    originalPrice: 29.0,
    image: "/img/tazas/img9.jpg",
    category: "tazas",
    franchise: "Chainsaw Man",
    rating: 4.4,
    reviews: 51,
    description: "Estilo agresivo con ilustración en rojo oscuro.",
  },
  {
    id: 40,
    name: "Taza Death Note Ryuk",
    price: 20.49,
    originalPrice: 27.0,
    image: "/img/tazas/img10.jpg",
    category: "tazas",
    franchise: "Death Note",
    rating: 4.7,
    reviews: 65,
    description: "Taza negra con ilustración de Ryuk y manzana roja.",
  },

  // DECORATIVOS
  {
    id: 41,
    name: "Poster Decorativo Demon Slayer",
    price: 19.99,
    originalPrice: 30.0,
    image: "/img/decorativos/img1.jpg",
    category: "decorativos",
    franchise: "Demon Slayer",
    rating: 4.5,
    reviews: 78,
    description: "Poster de alta resolución de Tanjiro y Nezuko.",
  },
  {
    id: 42,
    name: "Cuadro Acrílico Naruto Hokage",
    price: 49.99,
    originalPrice: 65.0,
    image: "/img/decorativos/img2.jpg",
    category: "decorativos",
    franchise: "Naruto",
    rating: 4.6,
    reviews: 84,
    description: "Cuadro moderno de Naruto con fondo de Konoha.",
  },
  {
    id: 43,
    name: "Alfombra One Piece Thousand Sunny",
    price: 59.99,
    originalPrice: 80.0,
    image: "/img/decorativos/img3.jpg",
    category: "decorativos",
    franchise: "One Piece",
    rating: 4.7,
    reviews: 62,
    description: "Alfombra decorativa con el barco de Luffy.",
  },
  {
    id: 44,
    name: "Lámpara LED Goku Kamehameha",
    price: 34.99,
    originalPrice: 50.0,
    image: "/img/decorativos/img4.jpg",
    category: "decorativos",
    franchise: "Dragon Ball",
    rating: 4.8,
    reviews: 102,
    description: "Lámpara con silueta de Goku lanzando su ataque.",
  },
  {
    id: 45,
    name: "Reloj de Pared Bleach",
    price: 29.99,
    originalPrice: 40.0,
    image: "/img/decorativos/img5.jpg",
    category: "decorativos",
    franchise: "Bleach",
    rating: 4.6,
    reviews: 47,
    description: "Reloj con fondo de Ichigo Kurosaki en forma Hollow.",
  },
  {
    id: 46,
    name: "Vinilo Tokyo Revengers",
    price: 14.99,
    originalPrice: 25.0,
    image: "/img/decorativos/img6.jpg",
    category: "decorativos",
    franchise: "Tokyo Revengers",
    rating: 4.4,
    reviews: 39,
    description: "Vinilo decorativo con el logo Toman en negro.",
  },
  {
    id: 47,
    name: "Banner Chainsaw Man",
    price: 22.99,
    originalPrice: 35.0,
    image: "/img/decorativos/img7.jpg",
    category: "decorativos",
    franchise: "Chainsaw Man",
    rating: 4.5,
    reviews: 43,
    description: "Banner textil de Denji y Power en batalla.",
  },
  {
    id: 48,
    name: "Cuadro Fullmetal Alchemist Duo",
    price: 44.99,
    originalPrice: 60.0,
    image: "/img/decorativos/img8.jpg",
    category: "decorativos",
    franchise: "Fullmetal Alchemist",
    rating: 4.7,
    reviews: 40,
    description: "Edward y Alphonse Elric en pose icónica.",
  },
  {
    id: 49,
    name: "Poster Death Note Light vs L",
    price: 24.99,
    originalPrice: 35.0,
    image: "/img/decorativos/img9.jpg",
    category: "decorativos",
    franchise: "Death Note",
    rating: 4.8,
    reviews: 70,
    description: "Diseño minimalista de los dos genios enfrentados.",
  },
  {
    id: 50,
    name: "Cuadro Nezuko Kimetsu Art",
    price: 39.99,
    originalPrice: 55.0,
    image: "/img/decorativos/img10.jpg",
    category: "decorativos",
    franchise: "Demon Slayer",
    rating: 4.6,
    reviews: 58,
    description: "Cuadro estilo acuarela de Nezuko con fondo floral.",
  },
];
